## Common ##
spring.application.name=quiz-engine
# Show message if error
server.error.include-message=always

## Cache ##
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10000, expireAfterWrite=10m

## Database ##
# Optional for modern Spring
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=dn
spring.datasource.password=dn

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
# To see SQL queries
spring.jpa.show-sql=true

# H2  + Console settings
#spring.datasource.url=jdbc:h2:file:~/quizdb //H2
#spring.datasource.url=jdbc:postgresql://db:5432/quizdb
#spring.h2.console.enabled=true
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false
#spring.h2.console.path=/h2-console
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect //H2
# For use DB only in memory
#spring.datasource.url=jdbc:h2:mem:quizdb

# Spring Security
spring.security.user.name=dn
spring.security.user.password=dn

# Telegram
telegram.bot.token=${BOT_TOKEN}
telegram.bot.username=DN_QuestBot