## Common ##
spring.application.name=quiz-engine
# Show message if error
server.error.include-message=always

## Docker - disableled for now ##
spring.docker.compose.enabled=false

## Cache ##
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10000, expireAfterWrite=10m

## Database ##
# Next configuration automatically creates database and tables
# URL-????? JDBC ??? ??????????? ? ???? ?????? ? ?????????????? ? ???
spring.datasource.url=jdbc:h2:file:~/quizdb
# For use DB only in memory
#spring.datasource.url=jdbc:h2:mem:quizdb
# Optional for modern Spring
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dn
spring.datasource.password=pass

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# To see SQL queries
spring.jpa.show-sql=true

# H2 Console settings
spring.h2.console.enabled=true
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
spring.h2.console.path=/h2-console
